services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_DB: securitydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:  <Your password>
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD:  <Your password>
    ports:
      - "8082:80"
    depends_on:
      - postgres

volumes:
  pg_data:

