# Generated by Django 5.2.4 on 2025-08-04 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Production Year')),
            ],
            options={
                'verbose_name': 'Production Year',
                'verbose_name_plural': 'Production Years',
                'ordering': ['-year'],
            },
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='engine',
            options={'verbose_name': 'Engine', 'verbose_name_plural': 'Engines'},
        ),
        migrations.AlterModelOptions(
            name='fueltype',
            options={'verbose_name': 'Fuel Type', 'verbose_name_plural': 'Fuel Types'},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'verbose_name': 'Car Model', 'verbose_name_plural': 'Car Models'},
        ),
        migrations.AddField(
            model_name='engine',
            name='fuel_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.fueltype', verbose_name='Fuel Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Engine Type'),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Fuel Type Name'),
        ),
        migrations.AlterField(
            model_name='model',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Model Name'),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.engine', verbose_name='Engine')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.model', verbose_name='Model')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.year', verbose_name='Production Year')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.DeleteModel(
            name='CarConfiguration',
        ),
    ]
