# Generated by Django 5.2.4 on 2025-08-06 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_searchquery_searchresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchresult',
            options={'ordering': ['-created_at'], 'verbose_name': 'Search Result', 'verbose_name_plural': 'Search Results'},
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='relevance_score',
        ),
    ]
