# Generated by Django 5.2.4 on 2025-08-06 19:52

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('pages', '0004_alter_searchresult_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='CarModel',
        ),
    ]

