# Generated by Django 5.2.4 on 2025-08-06 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20250806_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.engine', verbose_name='Engine'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.carmodel', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.year', verbose_name='Production Year'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='fuel_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.fueltype', verbose_name='Fuel Type'),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Fuel Type Name'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.car', verbose_name='Car'),
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together={('name', 'brand')},
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['name'], name='pages_brand_name_853257_idx'),
        ),
        migrations.AddIndex(
            model_name='fueltype',
            index=models.Index(fields=['name'], name='pages_fuelt_name_22cc39_idx'),
        ),
    ]
