server:
  port: 8777
  forward-headers-strategy: framework
  servlet:
    context-path: /api

spring:
  application:
    name: test-security_service

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 200ms
      timeout: 200ms

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs

cors:
  allowed-origins: http://localhost

token:
  access-token-expiration-ms: 900000
  max-tokens: 3

prefix:
  blocked: "test-block:"

rate:
  limit-ms:
    issue: 3000
    validate: 300


