server:
  port: ${PORT}
  forward-headers-strategy: framework
  servlet:
    context-path: /api

spring:
  application:
    name: security_service

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      connect-timeout: 200ms
      timeout: 200ms

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs

cors:
  allowed-origins: ${ALLOWED_ORIGINS}

token:
  access-token-expiration-ms: ${ACCESS_TOKEN_EXPIRATION_MS}
  max-tokens: ${MAX_TOKEN}

prefix:
  blocked: ${BLOCKED_PREFIX}

rate:
  limit-ms: ${RATE_LIMIT}