server:
  port: ${PORT}
  forward-headers-strategy: framework
  servlet:
    context-path: /api

spring:
  application:
    name: security_service

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:securitydb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      connect-timeout: 200ms
      timeout: 200ms

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs

cors:
  allowed-origins: ${ALLOWED_ORIGINS}

token:
  access-token-expiration-ms: ${ACCESS_TOKEN_EXPIRATION_MS}
  max-tokens: ${MAX_TOKEN}

prefix:
  blocked: ${BLOCKED_PREFIX}

rate:
  limit-ms:
    issue: ${ISSUE_RATE_LIMIT}
    validate: ${VALIDATE_RATE_LIMIT}

log:
  dir: ${LOG_DIR}

archive:
  schedule:
    fixed-delay-ms: ${FIXED_DELAY_MS}
    initial-delay-ms: ${INITIAL_DELAY_MS}
