blank_issues_enabled: false

contact_links:
  - name: Need more help? Use Q&A Discussions
    url: https://github.com/orgs/in49-380/discussions/categories/q-a
    about: Please use the Q&A section in Discussions for questions and support.

  - name: Security vulnerability report
    url: https://github.com/in49-380/VORIQ/security/policy
    about: Report security issues privately via the Security Policy page.

  - name: Contribution guidelines
    url: https://github.com/in49-380/VORIQ/blob/main/CONTRIBUTING.md
    about: Read how we work, branch/commit rules, and PR expectations.
