server:
  port: ${PORT:8084}
  forward-headers-strategy: framework
  servlet:
    context-path: /api

spring:
  application:
    name: car_catalog_service

  datasource:
    voriq:
      url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB2_NAME:voriq_cars}
      username: ${DB_USERNAME:postgres}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  pg:
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:5432}
    admin-db: ${DB_ADMIN:postgres}
    app-db: ${DB2_NAME:voriq_cars}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}

springdoc:
  swagger-ui:
    path: /api/swagger-ui/index.html
    config-url: /car/api/v3/api-docs/swagger-config
    urls:
      - name: Car Catalog
        url: /car/api/v3/api-doc

cors:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:8080,http://127.0.0.1:8080}

tmp-token:
  1: ${TMP_TOKEN_1}
  2: ${TMP_TOKEN_2}
  3: ${TMP_TOKEN_3}
