server:
  port: 8787
  forward-headers-strategy: framework
  servlet:
    context-path: /api

spring:
  application:
    name: car_catalog_service

  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 200ms
      timeout: 200ms

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs

cors:
  allowed-origins: http://localhost