server:
  port: 8787
  forward-headers-strategy: framework
  servlet:
    context-path: /api

spring:
  application:
    name: car_catalog_service_test

  datasource:
    voriq:
      url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB2_NAME:voriq_cars}
      username: ${DB_USERNAME:postgres}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs

cors:
  allowed-origins: http://localhost

tmp-token:
  1: 33333333-3333-3333-3333-333333333333
  2: 44444444-4444-4444-4444-444444444444
  3: dddddddd-dddd-dddd-dddd-dddddddddddd
  prefix: "test-tmp-token: "