<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.company.tests</groupId>
    <artifactId>tests-parent</artifactId>
    <version>1.0</version>
    <packaging>pom</packaging>
    <name>Tests Parent (UI + API)</name>

    <modules>
        <module>ui</module>
        <module>rest-api</module>
    </modules>

    <!-- Общие свойства (опционально, но удобно) -->
    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>

        <!-- Единые папки Allure в корне -->
        <allure.shared.results>${project.basedir}/allure-results</allure.shared.results>
        <allure.shared.report>${project.basedir}/allure-report</allure.shared.report>
        <allure.shared.history>${project.basedir}/.allure/history</allure.shared.history>
    </properties>

    <!-- Профиль для сборки общего отчёта Allure из общих results -->
    <profiles>
        <profile>
            <id>allure-report</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>io.qameta.allure</groupId>
                        <artifactId>allure-maven</artifactId>
                        <version>2.12.0</version>
                        <configuration>
                            <!-- берём результаты/пишем отчёт в общие директории -->
                            <resultsDirectory>${allure.shared.results}</resultsDirectory>
                            <reportDirectory>${allure.shared.report}</reportDirectory>
                        </configuration>
                        <executions>
                            <execution>
                                <id>make-allure-report</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>report</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
