server:
  port: ${PORT}
  forward-headers-strategy: framework
  servlet:
    context-path: /api

spring:
  application:
    name: parser_service

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create   # на чистой БД: create / create-drop; на существующей — update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialectstgres

