server:
  port: ${PORT}
  forward-headers-strategy: framework
  servlet:
    context-path: /api/v1

spring:
  application:
    name: parser_service

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      platform: postgres

  jpa:
    hibernate:
      ddl-auto: none
