server:
  port: ${PORT}
  forward-headers-strategy: framework
  servlet:
    context-path: /api/v1

spring:
  application:
    name: parser_service

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create   # on clear DB: create / create-drop; on an existing DB — update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
