#baseURI.catalog=https://voriq.info/car/api
#baseURI.security=https://voriq.info/security/api
baseURI.catalog=http://voriq.info:8084/api
baseURI.security=http://voriq.info:8081/api
objectCarCatalog=/v1/catalog
objectCarBrands={objectCarCatalog}/brands
objectCarModels={objectCarCatalog}/brands/{brandId}/models
objectCarYears={objectCarCatalog}/brands/{brandId}/models/{modelId}/years
objectCarEngines={objectCarCatalog}/brands/{brandId}/models/{modelId}/years/{yearId}/engines
objectCarTransmissions={objectCarCatalog}/brands/{brandId}/models/{modelId}/years/{yearId}/engines/{engineId}/transmissions
objectCarWheelDrive={objectCarCatalog}/brands/{brandId}/models/{modelId}/years/{yearId}/engines/{engineId}/transmissions/{transmissionId}/wheel_drive
objectCarResolve={objectCarCatalog}/cars/resolve
objectTestController=/v1/test/delay-ms

brandId=2
modelId=2
yearId=1
engineId=1
transmissionId=1
wheelDriveId=1
carId=1

objectTokenValidator=/v1/tokens/validate
objectTokenIssuance=/v1/tokens/issue
token=8d74f2d1-4c2e-4c90-b58b-1ac9e3c0a527
tokenSecurityService=d3cc8ac7-38d6-4f6c-83c8-ecf37c843e8a

userId=11111111-1111-1111-1111-111111111111
key=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa

#userId=d089ea5e-b82e-4ef8-b1a0-693330e9e16d
#key=399f7caf-af39-465d-945e-c13d3bf63796

#userId=089ea5e-b82e-4ef8-b1a0-693330e9e16d
#key=399f7caf-af39-465d-945e-c13d3bf63796

