name: DEPRECATED Deploy Backend Java Security Service

on:
  push:
    branches:
      - '**'
    paths:
      - 'backend/java/security_service**'
      - 'devops/dev/backend/java/security_service**'
  workflow_dispatch:

concurrency:
  group: deploy-backend-java-security-service-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy backend to Server over SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.CICD_SSH_HOST }}
          username: ${{ secrets.CICD_SSH_USER }}
          key: ${{ secrets.CICD_SSH_PRIVATE_KEY }}
          script: |

            set -euo pipefail

            # set variables
            BRANCH="${{ github.ref_name }}"
            REPO_DIR="/home/${{ secrets.CICD_SSH_USER }}/VORIQ"
            #SERVICE_DIR="backend/java/security_service"
            IMAGE="dev_security_service"
            TAG_BRANCH="$(echo "$BRANCH" | tr '[:upper:]' '[:lower:]' | sed -E 's#[^a-z0-9_.-]+#-#g' | sed -E 's#^-+|-+$##g' | cut -c1-120)-latest"
            TAG_SHA="${{ github.sha }}"
            TAG_LAT="latest"
            TAG=$TAG_LAT
            CONTAINER="dev_security_service" 

            # Ensure the VORIQ directory exists
            [ -d "$REPO_DIR/.git" ] || git clone https://github.com/in49-380/VORIQ.git "$REPO_DIR"

            # Change to the VORIQ directory
            cd "$REPO_DIR"

            # get the latest changes
            git fetch --all --prune
            git checkout -B "$BRANCH" "$TAG_SHA"
            git reset --hard "$TAG_SHA"
            git clean -fdx

            # go to the code directory
            cd /home/${{ secrets.CICD_SSH_USER }}/VORIQ/backend/java/security_service



            # build new image
            docker image build --no-cache \
              -t "$IMAGE:$TAG" \
              -f "$REPO_DIR/devops/dev/backend/java/security_service/Dockerfile" .

            #docker tag "$IMAGE:$TAG_SHA" "$IMAGE:$TAG_BRANCH"
            #docker tag "$IMAGE:$TAG_SHA" "$IMAGE:TAG_LAT"

            # remove old container if exists
            docker container stop "$CONTAINER" || true
            docker container rm -f "$CONTAINER" || true

            # running new docker container
            # IMAGE="dev_security_service" && \
            # TAG="latest" && \
            # CONTAINER="dev_security_service" && \
            docker container run -d \
            --restart unless-stopped \
            --name $CONTAINER \
            -p 8081:8081 \
            -v "$CONTAINER"_log:/opt/app/logs \
            -e SPRING_PROFILES_ACTIVE=dev \
            -e PORT=8081 \
            -e DB_HOST=172.18.0.2 \
            -e DB_PORT=5432 \
            -e DB_NAME=users \
            -e DB_USERNAME=postgres \
            -e DB_PASSWORD=postgres \
            -e REDIS_HOST=172.17.0.5 \
            -e REDIS_PORT=6379 \
            -e ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,http://voriq.info:3000,http://172.17.0.3:3000 \
            -e ACCESS_TOKEN_EXPIRATION_MS=900000 \
            -e MAX_TOKEN=5 \
            -e ISSUE_RATE_LIMIT=5000 \
            -e VALIDATE_RATE_LIMIT=300 \
            -e BLOCKED_PREFIX="block:" \
            -e LOG_PATH=/opt/app/logs \
            -e JAVA_OPTS="-XX:+ExitOnOutOfMemoryError -XX:MaxRAMPercentage=75 -XX:+UseStringDeduplication -Duser.timezone=Europe/Berlin" \
            -e LOG_DIR=/opt/app/logs \
            -e FIXED_DELAY_MS=259200000 \
            -e INITIAL_DELAY_MS=60000 \
            $IMAGE:$TAG && \
            docker network connect dbnetwork $CONTAINER

            # clean up old images to save space
            #docker image prune -f 
            # remove dangling images
            #docker image prune -f --filter "dangling=true"
            # another remove string
            docker image rm -f $(docker image ls -aq) || true
            # if images wont be deleted, uncomment the next line
            #docker image ls "$IMAGE" -q | xargs -n 1 docker rmi -f