name: Deploy Frontend Node

on:
  push:
    branches:
      - '**'
    paths:
      - 'frontend/**'
      - 'devops/dev/frontend/**'
  workflow_dispatch:

concurrency:
  group: deploy-frontend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy frontend to server over SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.CICD_SSH_HOST }}
          username: ${{ secrets.CICD_SSH_USER }}
          key: ${{ secrets.CICD_SSH_PRIVATE_KEY }}
          script: |

            set -euo pipefail

            # set variables
            BRANCH="${{ github.ref_name }}"
            REPO_DIR="/home/${{ secrets.CICD_SSH_USER }}/VORIQ"
            #SERVICE_DIR="devops/frontend"
            IMAGE="dev_front_node"
            TAG_BRANCH="$(echo "$BRANCH" | tr '[:upper:]' '[:lower:]' | sed -E 's#[^a-z0-9_.-]+#-#g' | sed -E 's#^-+|-+$##g' | cut -c1-120)-latest"
            TAG_SHA="${{ github.sha }}"
            TAG_LAT="latest"
            TAG=$TAG_LAT
            CONTAINER="dev_front_node"

            # Ensure the VORIQ directory exists
            [ -d "$REPO_DIR/.git" ] || git clone https://github.com/in49-380/VORIQ.git "$REPO_DIR"

            # Change to the VORIQ directory
            cd "$REPO_DIR"

            # get the latest changes
            git clean -fdx
            git reset --hard
            git fetch --all --prune
            git checkout -B "$BRANCH" "$TAG_SHA"
            git pull origin "$BRANCH"

            # go to the code directory  
            cd "$REPO_DIR/frontend"
        
            # prepare .enf for front
            echo '${{ secrets.DEV_FRONT_GOOGLE_CLIENT_ID }}' > .env
            echo "VITE_SWAGGER_DOMAIN=http://172.17.0.8" >> .env
            echo "VITE_SWAGGER_PORT=8084" >> .env

            # go to the infrastructure directory  
            cd "$REPO_DIR/devops"

            # prepare .enf for infrastructure
            rm -f .env
            echo 'DB_NAME=${{ secrets.DB_NAME }}' >> .env
            echo 'DB_USERNAME=${{ secrets.DB_USERNAME }}' >> .env
            echo 'DB_PASSWORD=${{ secrets.DB_PASSWORD }}' >> .env
            echo 'DB_NAME_SECURITY=${{ secrets.DB_NAME_SSERVICE }}' >> .env
            echo 'DB_NAME_CAR=${{ secrets.DB_NAME_CAR }}' >> .env
            echo 'DB_NAME_PARSER=${{ secrets.DB_NAME_PARSER }}' >> .env
            
            # build new image and restart container with new image
            ENV=dev && ENV=$ENV docker compose --env-file .env --env-file .env."$ENV" up -d --no-deps --build front-node

            # clean up old images to save space
            #docker image prune -f 
            # remove dangling images
            #docker image prune -f --filter "dangling=true"
            # another remove string
            docker image rm -f $(docker image ls -aq) || true
            # if images wont be deleted, uncomment the next line
            #docker image ls "$IMAGE" -q | xargs -n 1 docker rmi -f


            # wait few seconds, until container is run
            sleep 20

            # get container id of the just started container
            CONTAINER_ID=$(ENV=dev && ENV=$ENV docker compose --env-file .env --env-file .env."$ENV" ps -q front-node)

            # checking container status.
            if [ "$(docker inspect -f {{.State.Running}} $CONTAINER_ID)" != "true" ] || [ "$(docker inspect -f {{.State.Restarting}} $CONTAINER_ID)" = "true" ] ; then
                echo " "
                echo " "
                echo " "
                echo " "
                echo " "
                echo "!!!!!!!!! Container failed to start. Capturing logs... !!!!!!!!" >&2
                # getting last log strings.
                docker logs --tail 100 $CONTAINER_ID 2>&1
            
                # exiting with failure, so all job ends with failure.
                exit 1 
            fi



  notify_on_failure:
    runs-on: ubuntu-latest
    needs: build_and_deploy
    if: failure()
    steps:
      - name: Send a Discord notification
        uses: appleboy/discord-action@master
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }} # WebHook URL
          # webhook_id: ${{ secrets.DISCORD_WEBHOOK_URL }} # WebHook ID
          # webhook_token: ${{ secrets.DISCORD_WEBHOOK_URL }} # WebHook Token
          message: |
            :x: **Deploy is failed!**
            
            **Repo**: `${{ github.repository }}`
            **Branch**: `${{ github.ref_name }}`
            **Commit**: `${{ github.sha }}`
            **Run ID**: `${{ github.run_id }}`
            **Deploy log link address**: `${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`
            **Deploy log direct link**: [LOGS](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

