name: LOG parser

on:
  workflow_dispatch:


jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    outputs:
      container_logs: ${{ steps.set_logs_output.outputs.container_logs }}
    steps:
      - name: Deploy backend to Server over SSH
        id: deploy_and_check
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.CICD_SSH_HOST }}
          username: ${{ secrets.CICD_SSH_USER }}
          key: ${{ secrets.CICD_SSH_PRIVATE_KEY }}
          script: |

                docker logs --tail 5 dev-back-java-parser 2>&1
                uname -a


      - name: Set logs output for failed run
        id: set_logs_output
        # if: failure()
        run: |

          echo "${{ steps.deploy_and_check.outputs.stdout }}"
          LOGS_FROM_SSH="${{ steps.deploy_and_check.outputs.stdout }}"

          # LOGS_FROM_SSH="${{ steps.deploy_and_check.outputs.container_logs }}"
          # echo "container_logs<<EOF" >> $GITHUB_OUTPUT
          # echo "$LOGS_FROM_SSH" >> $GITHUB_OUTPUT
          # echo "EOF" >> $GITHUB_OUTPUT
          # v2
          echo "container_logs=$LOGS_FROM_SSH" >> $GITHUB_OUTPUT
