name: LOG parser

on:
  workflow_dispatch:


jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    outputs:
      container_logs: ${{ steps.set_logs_output.outputs.container_logs }}
    steps:
      - name: Add SSH key to agent
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.CICD_SSH_PRIVATE_KEY }}


      - name: Get container logs over SSH
        id: get_logs_from_server
        # Здесь вы явно указываете имя пользователя, хост и команду
        # Весь вывод команды будет захвачен в steps.get_logs_from_server.outputs.stdout
        run: |
          var_1_data="$(ssh -o StrictHostKeyChecking=no ${{ secrets.CICD_SSH_USER }}@${{ secrets.CICD_SSH_HOST }} 'docker logs --tail 50 dev-back-java-parser 2>&1')"
          echo "$var_1_data"
          echo "var_1=$var_1_data" >> $GITHUB_OUTPUT
    

      - name: Set logs output for failed run
        id: set_logs_output
        # if: failure()
        run: |

          echo "1 ${{ steps.deploy_and_check.outputs.stdout }}"
          echo "2 ${{ steps.get_logs_from_server.outputs.stdout }}"
          echo "3 ${{ steps.get_logs_from_server.outputs.var_1 }} | base64 --decode"

          LOGS_FROM_SSH="${{ steps.deploy_and_check.outputs.stdout }}"

          # LOGS_FROM_SSH="${{ steps.deploy_and_check.outputs.container_logs }}"
          # echo "container_logs<<EOF" >> $GITHUB_OUTPUT
          # echo "$LOGS_FROM_SSH" >> $GITHUB_OUTPUT
          # echo "EOF" >> $GITHUB_OUTPUT
          # v2
          echo "container_logs=$LOGS_FROM_SSH" >> $GITHUB_OUTPUT
