name: Deploy Frontend

on:
  push:
    branches: ['**']
    paths:
      - 'frontend/**'
      - 'devops/frontend/**'
  workflow_dispatch:

concurrency:
  group: deploy-frontend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.CICD_SSH_HOST }}
          username: ${{ secrets.CICD_SSH_USER }}
          key: ${{ secrets.CICD_SSH_PRIVATE_KEY }}
          script: |
            set -Eeuo pipefail

            BRANCH="${{ github.ref_name }}"
            REPO_DIR="/home/${{ secrets.CICD_SSH_USER }}/VORIQ"
            IMAGE="dev_front_node"
            SHA_TAG="${{ github.sha }}"
   
            BRANCH_TAG="$(echo "$BRANCH" | tr '[:upper:]' '[:lower:]' | sed -E 's#[^a-z0-9_.-]+#-#g' | sed -E 's#^-+|-+$##g' | cut -c1-120)-latest"
            CONTAINER="dev_front_node"

            [ -d "$REPO_DIR/.git" ] || git clone https://github.com/in49-380/VORIQ.git "$REPO_DIR"
            cd "$REPO_DIR"
            git fetch --all --prune
            git checkout -B "$BRANCH" "origin/$BRANCH"
            git reset --hard "origin/$BRANCH"
            git clean -fdx

            cd "$REPO_DIR/frontend"
            echo '${{ secrets.DEV_FRONT_GOOGLE_CLIENT_ID }}' > .env

            docker build --pull --no-cache \
              -t "$IMAGE:$SHA_TAG" \
              -f "$REPO_DIR/devops/frontend/Dockerfile.front.develop" .

            docker tag "$IMAGE:$SHA_TAG" "$IMAGE:$BRANCH_TAG"
            docker tag "$IMAGE:$SHA_TAG" "$IMAGE:latest"

            docker rm -f "$CONTAINER" 2>/dev/null || true
            docker run -d --name "$CONTAINER" --restart unless-stopped \
              -p 3000:3000 \
              "$IMAGE:$SHA_TAG"

            docker image prune -f
