name: Validate Branch Name

on:
  pull_request:
    branches:
      - '*'

jobs:
  validate_branch_name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Github Variables
        run: |
          echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_REF#: $GITHUB_REF#refs/heads/"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          BRANCH_NAME=${GITHUB_HEAD_REF}
          echo "BRANCH_NAME: $BRANCH_NAME"

      - name: Get branch name
        id: get_branch
        run: |
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            BRANCH_NAME=${GITHUB_HEAD_REF}
          else
            BRANCH_NAME=${GITHUB_REF#refs/heads/}
          fi
          echo "BRANCH_NAME: $BRANCH_NAME"

      - name: Validate Branch Name
        run: |
          echo "BRANCH_NAME: $BRANCH_NAME"
          if [[ "$BRANCH_NAME" =~ ^(feature|bugfix|hotfix|refactor|test|docs|chore)\/\d+-.{10,}$ ]]; then
            echo "Branch name '$BRANCH_NAME' is valid."
            exit 0 
          else
            echo "Branch name '$BRANCH_NAME' is invalid. It must match the pattern: <type>/<issue-id>-<short-description>"
            echo "Available <type>: feature|bugfix|hotfix|refactor|test|docs|chore"
            exit 1 
          fi
