name: Validate Branch and Commit Naming

on:
  push:
    branches:
      - dev
      - '*'
  pull_request:
    branches:
      - dev

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate branch name
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          if [[ ! "$BRANCH_NAME" =~ ^(feature|bugfix|hotfix|refactor|test|docs)/[0-9]+-[a-z0-9-]+$ ]]; then
            echo "Branch name '$BRANCH_NAME' does not follow the naming convention."
            echo "Expected format: <type>/<issue-id>-<short-description>"
            exit 1
          fi

      - name: Validate commit messages
        run: |
          COMMIT_MESSAGES=$(git log origin/${{ github.event.before }}..HEAD --pretty=format:"%s")
          echo "$COMMIT_MESSAGES" | while read -r message; do
            if [[ ! "$message" =~ ^(feature|bugfix|hotfix|refactor|test|docs):\ #[0-9]+\ .{1,72} ]]; then
              echo "Commit message '$message' does not follow the naming convention."
              echo "Expected format: <type>: #<issue-id> <short summary>"
              exit 1
            fi
            FIRST_LINE=$(echo "$message" | head -n 1)
            if [ ${#FIRST_LINE} -gt 72 ]; then
              echo "First line of commit message '$FIRST_LINE' exceeds 72 characters."
              exit 1
            fi
          done

      - name: Success message
        run: echo "All branch names and commit messages are valid!"