name: Validate Branch Name

on:
  pull_request:
    branches:
      - '*'

jobs:
  validate_branch_name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get branch name
        id: get_branch
        run: |
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            BRANCH_NAME=${GITHUB_HEAD_REF}
          else
            BRANCH_NAME=${GITHUB_REF#refs/heads/}
          fi
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Validate branch name
        id: validate_branch_name
        run: |
          echo "BRANCH_NAME=$BRANCH_NAME"
          if [[ "$BRANCH_NAME" =~ ^(feature|bugfix|hotfix|refactor|test|docs|chore)\/[0-9]+-[a-z0-9-]{5,}$ ]]; then
            echo "Branch name '$BRANCH_NAME' is valid."
            exit 0 
          else
            echo "Branch name '$BRANCH_NAME' is invalid. It must match the pattern: <type>/<issue-id>-<short-description>"
            echo "Available <type>: feature|bugfix|hotfix|refactor|test|docs|chore"
            exit 1 
          fi
        env: 
          BRANCH_NAME: ${{ env.BRANCH_NAME }}

      - name: Validate commit messages
        run: |
          COMMIT_MESSAGE=$(git log -n 1 --format=%B)
            if [[ ! "$COMMIT_MESSAGE" =~ ^(feature|bugfix|hotfix|refactor|test|docs):\ #[0-9]+\ .{1,72} ]]; then
              echo "Commit message '$COMMIT_MESSAGE' does not follow the naming convention."
              echo "Expected format: <type>: #<issue-id> <short summary>"
              exit 1
            fi
